site:
  name: Sample website
  locales: [en]
  seo_title: A simple LocomotiveCMS website
  meta_keywords: some meta keywords
  meta_description: some meta description

  pages:
  - "index":
      title: Home page
  - "404":
      title: Page not found